### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by Infl1ght** [danilosalvati/svd-js#1]
I'm trying to install package, but I got error: "\node_modules\node-svd\svdutil.c(40): fatal error C1083: netinet/in.h: No such file or directory".

**Comment by danilosalvati** [comment]
Hi @Infl1ght,
It works for me with node 10. What node version are you using?

**Comment by Infl1ght** [comment]
v10.15.0
Maybe it's because I'm working with Windows.

**Comment by danilosalvati** [comment]
Hi @Infl1ght,
sorry for the late response but I tried also with windows and package works perfectly for me
